import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353535",
        "on-tertiary": "#001e2b",
        "tertiary-container": "#3e9ac1",
        "secondary": "#89ceff",
        "on-secondary": "#001e2f",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "on-secondary-container": "#c9e6ff",
        "on-secondary-fixed-variant": "#00405d",
        "on-secondary-fixed": "#001e2f",
        "primary-container": "#a2dcff",
        "surface-container-low": "#1b1b1b",
        "tertiary-fixed-dim": "#004d66",
        "inverse-primary": "#00668a",
        "inverse-on-surface": "#303030",
        "on-primary-container": "#000000",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#001e2c",
        "secondary-container": "#004c6e",
        "on-tertiary-container": "#000000",
        "on-tertiary-fixed": "#ffffff",
        "on-surface": "#e2e2e2",
        "secondary-fixed-dim": "#34b5fa",
        "tertiary-fixed": "#006686",
        "secondary-fixed": "#89ceff",
        "surface": "#131313",
        "primary": "#ffffff",
        "surface-bright": "#393939",
        "surface-container": "#1f1f1f",
        "tertiary": "#c0e8ff",
        "on-surface-variant": "#c6c6c6",
        "inverse-surface": "#e2e2e2",
        "outline-variant": "#474747",
        "surface-tint": "#7bd0ff",
        "background": "#131313",
        "outline": "#919191",
        "on-background": "#e2e2e2",
        "on-primary-fixed": "#ffffff",
        "surface-container-highest": "#353535",
        "on-primary-fixed-variant": "#c4e7ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#c0e8ff",
        "error": "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#00668a",
        "primary-fixed-dim": "#004c69",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
